apiVersion: v1
kind: Service
metadata:
  name: personal-app-service
  namespace: dev  
spec:
  selector:
    app: personal-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP



