apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-app
  namespace: dev 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-app
  template:
    metadata:
      labels:
        app: personal-app
    spec:
      containers:
        - name: personal-app
          image: 416591745024.dkr.ecr.eu-west-2.amazonaws.com/personal-demo/personal-app:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
